#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# path to self and parent dir
SCRIPT=$(realpath $0)
SCRIPTPATH=$(dirname $SCRIPT)

# check platform
if uname -a | grep -q Darwin; then
  PLATFORM="macos"
elif uname -a | grep -q Linux; then
  PLATFORM="linux"
else
  echo "Unsupported platform"
  exit 1
fi

# check architecture
if uname -a | grep -q x86_64; then
  ARCH="amd64"
elif uname -a | grep -q 'arm64\|aarch64'; then
  ARCH="arm64"
else
  echo "Unsupported architecture"
fi

# check for sudo and get sudo
if (sudo -n false >/dev/null 2>&1); then
  sudo -p "Provide sudo password: " echo "Sudo password auto-refresh started..."
  # background sudo revalidate until script ends
  {
    while /bin/sleep 290; do
      sudo -v
      echo -e "\nrefreshing sudo timeout"
    done
  } &
  SUDO_PID=$!
fi

# kill all child proceses quietly
kill_spawn() {
  for SPAWN in $(pgrep -g $$); do
    kill $SPAWN
  done
}

# kill_spawn on exit and ctrl-c
trap kill_spawn EXIT SIGINT

# list of packages to install
PACKAGES=(
  "git"
  "bash"
  "wget"
  "jq"
  "python310"
  "py310-pip"
  "py310-powerline"
  "py310-virtualenv"
  "py310-powerline"
)

## setup macOS
# test for macos platform
if [[ $PLATFORM == "macos" ]]; then

  # test for xcode command line tools
  if ! xcode-select -p &>/dev/null; then
    echo "Installing xcode command line tools..."
    xcode-select --install
    sudo xcode-select -s /Library/Developer/CommandLineTools
  fi

  # get latest release version from github for macports
  PORT_LATEST_RELEASE=$(curl -s https://api.github.com/repos/macports/macports-base/releases/latest | grep tag_name | cut -d '"' -f 4)
  PORT_LATEST_RELEASE_NUMBER=${PORT_LATEST_RELEASE#v}

  # get macOS operating system version long name including california parks using system_profiler
  MACOS_VERSION=$(sw_vers --ProductVersion | cut -d . -f1)
  MACOS_VERSION_NAME=$(awk '/SOFTWARE LICENSE AGREEMENT FOR macOS/' '/System/Library/CoreServices/Setup Assistant.app/Contents/Resources/en.lproj/OSXSoftwareLicense.rtf' | awk -F 'macOS ' '{print $NF}' | awk '{print substr($0, 0, length($0)-1)}')

  # test for macports
  if ! command -v /opt/local/bin/port &>/dev/null; then
    echo "Installing macports..."
    MACPORTS_PKG="https://github.com/macports/macports-base/releases/download/${PORT_LATEST_RELEASE}/MacPorts-${PORT_LATEST_RELEASE_NUMBER}-${MACOS_VERSION}-${MACOS_VERSION_NAME}.pkg"
echo $MACPORTS_PKG
    curl -L -o /tmp/macports.pkg $MACPORTS_PKG
    sudo installer -pkg /tmp/macports.pkg -target /
    rm /tmp/macports.pkg
  fi

  # install packages
  for PACKAGE in "${PACKAGES[@]}"; do
    if port installed $PACKAGE | grep -q "None of the specified ports are installed"; then
      echo "Installing $PACKAGE..."
      sudo /opt/local/bin/port -q install $PACKAGE
    fi
  done

  # setup dotfiles

  # set bash 5 as default shell
  if [[ -e /opt/local/bin/bash ]]; then
    sudo chsh -s /opt/local/bin/bash $USER
  fi

fi
