#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# path to self and parent dir
SCRIPT=$(realpath $0)
SCRIPTPATH=$(dirname $SCRIPT)

# set go version
GO_VERSION="1.19.9"

# check platform
if uname -a | grep -q Darwin; then
  PLATFORM="macos"
elif uname -a | grep -q Linux; then
  PLATFORM="linux"
else
  echo "Unsupported platform"
  exit 1
fi

# check architecture
if uname -a | grep -q x86_64; then
  ARCH="amd64"
elif uname -a | grep -q 'arm64\|aarch64'; then
  ARCH="arm64"
else
  echo "Unsupported architecture"
fi

# check for sudo and get sudo
if (sudo -n false >/dev/null 2>&1); then
  sudo -p "Provide sudo password: " echo "Sudo password auto-refresh started..."
  # background sudo revalidate until script ends
  {
    while /bin/sleep 290; do
      sudo -v
      echo -e "\nrefreshing sudo timeout"
    done
  } &
  SUDO_PID=$!
fi

# kill all child proceses quietly
kill_spawn() {
  for SPAWN in $(pgrep -g $$); do
    kill $SPAWN
  done
}

# kill_spawn on exit and ctrl-c
trap kill_spawn EXIT SIGINT

# list of packages to install
PORT_PACKAGES=(
  "git"
  "bash"
  "wget"
  "jq"
  "python310"
  "py310-pip"
  "py310-powerline"
  "py310-virtualenv"
  "py310-powerline"
)

# list of pip packages to install
PIP_PACKAGES=(
  "powerline-status"
  "virtualenv"
)

# list of apt packages to install
APT_PACKAGES=(
  "git"
  "bash"
  "wget"
  "jq"
  "python3.10"
  "python3.10-pip"
  "python3.10-venv"
  "powerline"
)

# setup a golang packages array
typeset -A GO_PACKAGES
GO_PACKAGES["mc"]="github.com/minio/mc@latest"
GO_PACKAGES["duf"]="github.com/muesli/duf@latest"
GO_PACKAGES["fzf"]="github.com/junegunn/fzf@latest"
GO_PACKAGES["age"]="filippo.io/age/cmd/...@latest"
GO_PACKAGES["vault-token-helper"]="github.com/joemiller/vault-token-helper@latest"

## do macOS specific stuff
if [[ $PLATFORM == "macos" ]]; then

  # test for xcode command line tools
  if ! xcode-select -p &>/dev/null; then
    echo "Installing xcode command line tools..."
    xcode-select --install
    sudo xcode-select -s /Library/Developer/CommandLineTools
  fi

  # get latest release version from github for macports
  PORT_LATEST_RELEASE=$(curl -s https://api.github.com/repos/macports/macports-base/releases/latest | grep tag_name | cut -d '"' -f 4)
  PORT_LATEST_RELEASE_NUMBER=${PORT_LATEST_RELEASE#v}

  # get macOS operating system version long name including california parks using system_profiler
  MACOS_VERSION=$(sw_vers --ProductVersion | cut -d . -f1)
  MACOS_VERSION_NAME=$(awk '/SOFTWARE LICENSE AGREEMENT FOR macOS/' '/System/Library/CoreServices/Setup Assistant.app/Contents/Resources/en.lproj/OSXSoftwareLicense.rtf' | awk -F 'macOS ' '{print $NF}' | awk '{print substr($0, 0, length($0)-1)}')

  # test for macports
  if ! command -v /opt/local/bin/port &>/dev/null; then
    echo "Installing macports..."
    MACPORTS_PKG="https://github.com/macports/macports-base/releases/download/${PORT_LATEST_RELEASE}/MacPorts-${PORT_LATEST_RELEASE_NUMBER}-${MACOS_VERSION}-${MACOS_VERSION_NAME}.pkg"
    echo $MACPORTS_PKG
    curl -L -o /tmp/macports.pkg $MACPORTS_PKG
    sudo installer -pkg /tmp/macports.pkg -target /
    rm /tmp/macports.pkg
  fi

  # install packages
  for PORT_PACKAGE in "${PORT_PACKAGES[@]}"; do
    if port installed $PORT_PACKAGE | grep -q "None of the specified ports are installed"; then
      echo "Installing $PORT_PACKAGE..."
      sudo /opt/local/bin/port -q install $PORT_PACKAGE
    fi
  done

  # setup dotfiles

  # set bash 5 as default shell
  if [[ -e /opt/local/bin/bash ]]; then
    sudo chsh -s /opt/local/bin/bash $USER
  fi

fi

## do linux specific stuff
if [[ $PLATFORM == "linux" ]]; then
  echo "Linux setup"
  # check to see if golang is installed and install if not
  if ! command -v go &>/dev/null; then
    echo "Installing golang..."
    wget -q -O go${GO_VERSION}.linux-${ARCH}.tar.gz https://golang.org/dl/go${GO_VERSION}.linux-${ARCH}.tar.gz
    sudo tar -C /usr/local -xzf go${GO_VERSION}.linux-${ARCH}.tar.gz
    PATH=$PATH:/usr/local/go/bin
    go version
    rm go${GO_VERSION}.linux-${ARCH}.tar.gz
    export GOPATH=${HOME}/code/go
  fi

  # loop through the array and print the values
  for key in "${!GO_PACKAGES[*]}"; do
    #echo ${key} ${GO_PACKAGES[${key}]}
    # check to see if packages is installed and install if not
    if ! command -v ${key} &>/dev/null; then
      echo "Installing ${key}..."
      go install ${GO_PACKAGES[${key}]}
    fi
  done

  # loop over pip packages and install them
  pip3 list --format=columns >~/.pip3_list
  for PIP_PACKAGE in "${PIP_PACKAGES[@]}"; do
    if ! grep -q $PIP_PACKAGE ~/.pip3_list; then
      echo "Installing $PIP_PACKAGE..."
      pip3 install --user $PIP_PACKAGE
    fi
  done
  rm ~/.pip3_list

  # # loop over apt packages and install them
  # for APT_PACKAGE in "${APT_PACKAGES[@]}"; do
  #   if ! dpkg -l | grep -q $APT_PACKAGE; then
  #     echo "Installing $APT_PACKAGE..."
  #     sudo apt-get install -y $APT_PACKAGE
  #   fi
  # done

  # setup dotfiles

  # set bash 5 as default shell
  if [[ -e /usr/bin/bash ]]; then
    sudo chsh -s /usr/bin/bash $USER
  fi

fi

## do common stuff

# if .fzf_completion is not present, download it
if [[ ! -e ${HOME}/.fzf_completion.bash ]]; then
  wget -q -O ${HOME}/.fzf_completion.bash https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.bash
  wget -q -O ${HOME}/.fzf_key-bindings.bash https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.bash
fi

# check for vault-token-helper and enable it
if command -v vault-token-helper &>/dev/null; then
  vault-token-helper enable
fi

exit 0
