#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# modern bash version check
! [ "${BASH_VERSINFO:-0}" -ge 4 ] && echo "This script requires bash v4 or later" && exit 1

# path to self and parent dir
SCRIPT=$(realpath $0)
SCRIPTPATH=$(dirname $SCRIPT)

# check for ~/.onepasswordenv
if [ -f ~/.onepasswordenv ]; then
  source ~/.onepasswordenv
else
  echo "~/.onepasswordenv not found"
  exit 1
fi

# example ~/.onepasswordenv file
# export VAULT_USERNAME="op://<VAULTID>/<ADOBENET_ACCOUNT_NAME>/username"
# export VAULT_PASSWORD="op://<VAULTID>/<ADOBENET_ACCOUNT_NAME>/password"

# Variables with default values
unset VAULT_TOKEN
VAULT_ADDR=${VAULT_ADDR:-https://nextbook.local:8200}
VAULT_NAMESPACE=${VAULT_NAMESPACE:-blake}
VAULT_AUTH_METHOD=${VAULT_AUTH_METHOD:-okta}
export OP_BIOMETRIC_UNLOCK_ENABLED=true

# using the 1password cli confirm that the op cli is signed in
if ! op whoami >/dev/null 2>&1; then
  echo "1Password CLI is not signed in"
  eval $(op signin)
fi

VAULT_USERNAME=$(op read "$ADOBENET_USERNAME")
VAULT_PASSWORD=$(op read "$ADOBENET_PASSWORD")

# test for vault connectivity using vault status command
if ! VAULT_STATUS=$(vault status -address=$VAULT_ADDR -format=json 2>&1); then
  echo "Failed to connect to Vault at $VAULT_ADDR"
  echo "$VAULT_STATUS"
  # Check for 403 Forbidden error
  if echo "$VAULT_STATUS" | grep -q "403 Forbidden"; then
    echo "Error 403: Check VPN connection"
    exit 1
  fi
  # check if vault is sealed using jq
  if echo "$VAULT_STATUS" | jq -e '.sealed == true' >/dev/null 2>&1; then
    echo "Vault is sealed"
    exit 1
  fi
fi

# renew the vault token using the vault token renew command if the token is expired login again
if vault token renew -address=$VAULT_ADDR -namespace=$VAULT_NAMESPACE >/dev/null 2>&1; then
  echo "Token renewed"
else
  echo "Vault token is expired, logging in again"
  # login to vault
  vault login -method=$VAULT_AUTH_METHOD -namespace=$VAULT_NAMESPACE -address=$VAULT_ADDR username="$VAULT_USERNAME" password="$VAULT_PASSWORD"
fi

exit 0
