#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# check if nrsc5 is running and kill it
if (pgrep nrsc5); then
  echo "stopping Kexp"
  pkill -15 nrsc5
  exit 0
fi

# check if dogle is local
echo "connecting to umac.jibb.tv"
nrsc5 -H umac.jibb.tv:9030 -g 6 90.3 0

exit 0