#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# modern bash version check
! [ "${BASH_VERSINFO:-0}" -ge 4 ] && echo "This script requires bash v4 or later" && exit 1

# set macports python version
PYTHON3VERSION="3.13"
PYTHON3VERSION_MPORTS=$(tr -d '.' <<<$PYTHON3VERSION)

# macports packages to install
PORT_PACKAGES=(
  "python${PYTHON3VERSION_MPORTS}"
  "py${PYTHON3VERSION_MPORTS}-pip"
  "py${PYTHON3VERSION_MPORTS}-virtualenv"
)

# install packages
for PORT_PACKAGE in "${PORT_PACKAGES[@]}"; do
  if /opt/local/bin/port installed $PORT_PACKAGE | grep -q "None of the specified ports are installed"; then
    echo "Installing $PORT_PACKAGE..."
    sudo /opt/local/bin/port -q install $PORT_PACKAGE
  fi
done

# fixups after port installation
if [[ -e /opt/local/bin/python${PYTHON3VERSION} ]]; then
  sudo /opt/local/bin/port select --set python python${PYTHON3VERSION_MPORTS} >/dev/null
  sudo /opt/local/bin/port select --set python3 python${PYTHON3VERSION_MPORTS} >/dev/null
  sudo /opt/local/bin/port select --set virtualenv virtualenv${PYTHON3VERSION_MPORTS} >/dev/null
  sudo /opt/local/bin/port select --set pip pip${PYTHON3VERSION_MPORTS} >/dev/null
  sudo /opt/local/bin/port select --set pip3 pip${PYTHON3VERSION_MPORTS} >/dev/null
fi

exit 0