#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# modern bash version check
! [ "${BASH_VERSINFO:-0}" -ge 4 ] && echo "This script requires bash v4 or later" && exit 1

PG_PIDS=$(pgrep GlobalProtect)

# for each PID found, kill it
for PID in ${PG_PIDS}; do
  echo "Killing GlobalProtect PID: ${PID}"
  ps -e "${PID}"
  sudo kill -9 "${PID}"
done

# /Library/LaunchDaemons/com.paloaltonetworks.gp.pangpsd.plist
sleep 5

open /Applications/GlobalProtect.app

exit 0