#!/bin/env bash

if ! command -v tee &>/dev/null; then
  echo "tee binary not found in path, exiting..."
  exit 1
fi

if [[ "$(uname)" == "Linux" ]]; then
  if ! [[ -f /etc/sudoers.d/admin ]]; then
    echo "Granting all admin users nopasswd sudo access..."
    echo "%admin ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/admin
  fi
fi

if [[ "$(uname)" == "Linux" ]]; then
  if ! [[ -f /etc/sudoers.d/adm ]]; then
    echo "Granting all admin users nopasswd sudo access..."
    echo "%adm ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/adm
  fi
fi