#!/bin/env bash
if [[ "$(uname)" == "Darwin" ]]; then
  if ! [[ -f /etc/sudoers.d/admin ]]; then
    echo "Hell yeah macOS doesn't have snapd!"
  fi
fi

if [[ "$(uname)" == "Linux" ]]; then
  if [[ -f /bin/running-in-container ]]; then
    echo "running in container"
  else
    if (dpkg -s snapd &>/dev/null); then
      sudo snap remove lxd
      sudo systemctl stop snapd
      sudo apt -y purge snapd
      rm -rf ~/snap
      sudo rm -rf /snap
      sudo rm -rf /var/snap
      sudo rm -rf /var/lib/snapd
    fi
  fi
fi

exit 0
