#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# check that this is running on ubuntu on arm64 architecture and exit if not
if ! [[ "$(uname -m)" == "aarch64" ]]; then
  echo "This script is only for ubuntu on arm64 architecture"
  exit 1
fi

# check for binutils-multiarch and install it if it's not installed
if ! dpkg -s binutils-multiarch >/dev/null 2>&1; then
  sudo apt install binutils-multiarch
fi

# install packages if they are not installed
if ! dpkg -s binfmt-support >/dev/null 2>&1; then
  sudo apt install binfmt-support
fi

# check if file exists and create it from heredoc if it doesn't
if [[ ! -f /etc/apt/sources.list.d/rosetta.list ]]; then

# update existing sources.list to explicly call out arm64 architecture
sed -i 's/deb http/deb [arch=arm64] http/' /etc/apt/sources.list
sed -i 's/deb-src http/deb [arch=arm64] http/' /etc/apt/sources.list

cat <<EOF | sudo tee /etc/apt/sources.list.d/rosetta.list >/dev/null
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy universe
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy multiverse
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-security main restricted
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-security universe
deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu jammy-security multiverse
EOF

sudo apt update
fi

# create rosseta mount point if it doesn't exist
if [[ ! -d /media/rosetta ]]; then
  sudo mkdir /media/rosetta
fi

# check id dpkg --add-architecture amd64 is already configured and if not then configure it
if ! dpkg --print-foreign-architectures | grep -q "amd64"; then
  sudo dpkg --add-architecture amd64
fi

# add rosetta mount point to /etc/fstab if it doesn't already exist
if ! grep -q "rosetta" /etc/fstab; then
  echo "rosetta	/media/rosetta	virtiofs	ro,nofail	0	0" | sudo tee -a /etc/fstab
fi

# mount rosetta if it's not already mounted
if ! mountpoint -q /media/rosetta; then
  sudo mount -t virtiofs rosetta /media/rosetta
fi


# check if rosetta is already configured and if not then configure it
add_rosetta_binfmt() {
  sudo update-binfmts --install rosetta /media/rosetta/rosetta --magic "\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00" --mask "\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff" --credentials yes --preserve no --fix-binary yes
}
if ! update-binfmts --display rosetta >/dev/null 2>&1; then
  add_rosetta_binfmt
fi

# likely redundant but will enable rosetta if it's not enabled and still installed
ROSETTA_STATUS=$(update-binfmts --display rosetta)
if ! [[ $ROSETTA_STATUS =~ "rosetta (enabled)" ]]; then
  add_rosetta_binfmt
fi

# get status of rosetta
/usr/sbin/update-binfmts --display rosetta

exit 0