#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# exit if os is not linux
if ! uname -a | grep -q Linux; then
  echo "This script is for Linux only"
  exit 1
fi

# update the apt cache
sudo apt update

# Install zeroconf packages
sudo apt install -y avahi-daemon avahi-utils libnss-mdns

# config avahi to publish on IPv6
sudo sed -i 's/use-ipv4=yes/use-ipv4=no/g' /etc/avahi/avahi-daemon.conf
sudo sed -i 's/#publish-addresses=yes/publish-addresses=yes/g' /etc/avahi/avahi-daemon.conf
sudo sed -i 's/#publish-a-on-ipv6=no/publish-a-on-ipv6=yes/g' /etc/avahi/avahi-daemon.conf

# enable and start zeroconf
sudo systemctl enable avahi-daemon
sudo systemctl start avahi-daemon

exit 0